from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import rawtherapee_pp3  # noqa: E402


class RawTherapeePP3Tests(unittest.TestCase):
    def test_parser_and_merge_preserve_unknown_sections_and_fields(self) -> None:
        base = rawtherapee_pp3.PP3Document.parse(
            """# generated by RawTherapee
[Exposure]
Compensation=0.5
UnknownFutureField=keep-me

[Future Module]
Enabled=true
OpaqueCurve=3;0;0;1;1;
""",
            source="base.pp3",
        )
        override = rawtherapee_pp3.PP3Document.parse(
            """[Exposure]
Compensation=1.25

[Lumenflow]
Compiler=test
""",
            source="override.pp3",
        )

        merged = base.merge(override)
        text = merged.to_text()

        self.assertIn("Compensation=1.25", text)
        self.assertIn("UnknownFutureField=keep-me", text)
        self.assertIn("[Future Module]", text)
        self.assertIn("OpaqueCurve=3;0;0;1;1;", text)
        self.assertEqual(merged.get("Exposure", "Compensation"), "1.25")

    def test_compile_profile_layers_starting_state_before_agent_overrides(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            base = root / "base.pp3"
            sidecar = root / "capture.RW2.pp3"
            base.write_text(
                "[Exposure]\nCompensation=0.2\n[Future]\nOpaque=one\n",
                encoding="utf-8",
            )
            sidecar.write_text(
                "[Exposure]\nContrast=3\n[Future]\nSecond=two\n",
                encoding="utf-8",
            )

            text = rawtherapee_pp3.compile_profile_text(
                [base, sidecar],
                overrides={"Exposure": {"Compensation": 0.75}},
            )
            document = rawtherapee_pp3.PP3Document.parse(text)

            self.assertEqual(document.get("Exposure", "Compensation"), "0.75")
            self.assertEqual(document.get("Exposure", "Contrast"), "3")
            self.assertEqual(document.get("Future", "Opaque"), "one")
            self.assertEqual(document.get("Future", "Second"), "two")
            self.assertEqual(document.get("Lumenflow", "Compiler"), rawtherapee_pp3.PP3_COMPILER_VERSION)

    def test_malformed_profile_fails_closed(self) -> None:
        with self.assertRaises(rawtherapee_pp3.PP3ParseError):
            rawtherapee_pp3.PP3Document.parse("Compensation=1\n")
        with self.assertRaises(rawtherapee_pp3.PP3ParseError):
            rawtherapee_pp3.PP3Document.parse("[Exposure]\nnot-a-field\n")

    def test_set_rejects_container_syntax_in_section_and_key(self) -> None:
        document = rawtherapee_pp3.PP3Document.empty()
        for section in ("[bad", "bad]", "bad=section", "bad\n", "bad\r", "bad\x00"):
            with self.subTest(section=section), self.assertRaises(
                rawtherapee_pp3.PP3UnsupportedValue
            ):
                document.set(section, "Key", "value")
        for key in ("[bad", "bad]", "bad=key", "bad\n", "bad\r", "bad\x00"):
            with self.subTest(key=key), self.assertRaises(rawtherapee_pp3.PP3UnsupportedValue):
                document.set("Section", key, "value")

    def test_semantic_mapping_does_not_expose_unverified_native_fields(self) -> None:
        with self.assertRaises(rawtherapee_pp3.PP3UnsupportedValue):
            rawtherapee_pp3.semantic_overrides(
                {"rawtherapee_native": {"Exposure": {"Compensation": 1}}}
            )

    def test_native_contract_accepts_only_fixture_verified_sections(self) -> None:
        contract = {
            "profile_version": 349,
            "sections": {
                "RAW": {
                    "CA": True,
                    "CAAutoIterations": 2,
                    "CAAvoidColourshift": True,
                },
                "RAW Bayer": {"Method": "rcd"},
                "HLRecovery": {"Enabled": True, "Method": "Luminance"},
                "Exposure": {
                    "Compensation": 0.35,
                    "Brightness": 4,
                    "Contrast": 12,
                    "Saturation": -4,
                    "Black": 20,
                    "HighlightCompr": 24,
                    "HighlightComprThreshold": 18,
                    "ShadowCompr": 18,
                    "CurveMode": "Standard",
                    "Curve": "3;0;0;0.35;0.2;0.7;0.85;1;1;",
                },
                "White Balance": {
                    "Enabled": True,
                    "Setting": "Custom",
                    "Temperature": 5200,
                    "Green": 1.01,
                },
                "Color appearance": {
                    "Enabled": True,
                    "Q-Contrast": 20,
                    "Q-Bright": -10,
                    "J-Light": 10,
                    "C-Chroma": 12,
                },
                "Directional Pyramid Denoising": {
                    "Enabled": True,
                    "Luma": 35,
                    "Ldetail": 20,
                    "Chroma": 25,
                    "Gamma": 2.0,
                    "Passes": 1,
                },
                "Vibrance": {"Enabled": True, "Pastels": 20, "Saturated": 10},
                "Shadows & Highlights": {
                    "Enabled": True,
                    "Highlights": 15,
                    "HighlightTonalWidth": 70,
                    "Shadows": 20,
                    "ShadowTonalWidth": 30,
                    "Radius": 20,
                },
                "Sharpening": {
                    "Enabled": True,
                    "Contrast": 50,
                    "Radius": 1.0,
                    "Amount": 250,
                },
                "Distortion": {"Amount": 35},
                "LensProfile": {
                    "LcMode": "lfauto",
                    "UseDistortion": True,
                    "UseVignette": True,
                    "UseCA": True,
                },
                "Rotation": {"Degree": 2.0},
                "Perspective": {"Horizontal": 5.0, "Vertical": -3.0},
                "Coarse Transformation": {"Rotate": 90, "HorizontalFlip": False},
                "Crop": {"Enabled": True, "X": 0, "Y": 0, "W": 4000, "H": 3000},
                "Resize": {"Enabled": True, "Scale": 0.5, "AllowUpscaling": False},
                "Color Management": {
                    "Gamut": True,
                    "OutputProfile": "RTv4_sRGB",
                    "OutputProfileIntent": "Relative",
                    "OutputBPC": True,
                },
            },
        }

        normalized = rawtherapee_pp3.validate_native_sections(contract)
        overrides = rawtherapee_pp3.native_sections_to_overrides(normalized)

        self.assertEqual(normalized["profile_version"], 349)
        self.assertEqual(overrides["RAW"]["CA"], True)
        self.assertEqual(overrides["Exposure"]["Curve"], contract["sections"]["Exposure"]["Curve"])
        self.assertEqual(overrides["White Balance"]["Temperature"], 5200)
        self.assertEqual(overrides["Vibrance"]["Pastels"], 20)
        self.assertEqual(overrides["Shadows & Highlights"]["Highlights"], 15)
        self.assertEqual(overrides["Perspective"]["Horizontal"], 5.0)
        self.assertEqual(overrides["Coarse Transformation"]["Rotate"], 90)
        self.assertEqual(overrides["Resize"]["Scale"], 0.5)

    def test_native_contract_fails_closed_for_unknown_fields_and_bad_values(self) -> None:
        base = {"profile_version": 349, "sections": {"RAW": {"CA": True}}}
        cases = [
            {**base, "profile_version": 348},
            {"profile_version": 349, "sections": {"Unknown": {"Enabled": True}}},
            {"profile_version": 349, "sections": {"RAW": {"Unknown": True}}},
            {"profile_version": 349, "sections": {"RAW": {"CA": 1}}},
            {"profile_version": 349, "sections": {"RAW": {"CAAutoIterations": 21}}},
            {
                "profile_version": 349,
                "sections": {"Exposure": {"CurveMode": "invented"}},
            },
            {
                "profile_version": 349,
                "sections": {"Exposure": {"Curve": "3;0;2;1;1;"}},
            },
            {
                "profile_version": 349,
                "sections": {"Coarse Transformation": {"Rotate": 45}},
            },
        ]
        for case in cases:
            with self.subTest(case=case), self.assertRaises(rawtherapee_pp3.PP3UnsupportedValue):
                rawtherapee_pp3.validate_native_sections(case)

    def test_native_boundary_values_match_schema_and_runtime(self) -> None:
        schema = json.loads(
            (ROOT / "knowledge" / "schemas" / "edit_intent.schema.json").read_text(
                encoding="utf-8"
            )
        )
        section_properties = schema["properties"]["style"]["properties"]["rawtherapee"][
            "properties"
        ]["sections"]["properties"]
        boundaries = {
            ("Directional Pyramid Denoising", "Gamma"): 0.1,
            ("Resize", "Scale"): 0.01,
            ("EPD", "Gamma"): 0.1,
            ("EPD", "Scale"): 0.0,
        }
        for (section, key), minimum in boundaries.items():
            with self.subTest(section=section, key=key):
                runtime_spec = rawtherapee_pp3.RAWTHERAPEE_NATIVE_FIELD_SPECS[section][key]
                self.assertEqual(runtime_spec.minimum, minimum)

                section_schema = schema
                ref_path = section_properties[section]["$ref"].removeprefix("#/")
                for component in ref_path.split("/"):
                    section_schema = section_schema[component]
                field_schema = section_schema["properties"][key]
                self.assertEqual(field_schema["minimum"], minimum)
                self.assertNotIn("exclusiveMinimum", field_schema)

                contract = {
                    "profile_version": 349,
                    "sections": {section: {key: minimum}},
                }
                normalized = rawtherapee_pp3.validate_native_sections(contract)
                self.assertEqual(normalized["sections"][section][key], minimum)

    def test_native_contract_rejects_empty_and_mutually_conflicting_input_shapes(self) -> None:
        for value in (
            None,
            {},
            {"profile_version": 349},
            {"profile_version": 349, "sections": {}},
            {"profile_version": 349, "sections": {"RAW": {}}},
        ):
            with self.subTest(value=value), self.assertRaises(rawtherapee_pp3.PP3UnsupportedValue):
                rawtherapee_pp3.validate_native_sections(value)

    def test_semantic_mapping_rejects_unknown_fields(self) -> None:
        with self.assertRaises(rawtherapee_pp3.PP3UnsupportedValue):
            rawtherapee_pp3.semantic_overrides({"exposure_compensation": 1, "invented": 2})

    def test_semantic_mapping_covers_current_intent_and_pixel_crop(self) -> None:
        overrides = rawtherapee_pp3.semantic_overrides(
            {
                "exposure_compensation": 0.35,
                "temperature": 5200,
                "green": 1.01,
            },
            composition={
                "decision": "crop",
                "crop": {
                    "unit": "pixels",
                    "x": 10,
                    "y": 20,
                    "width": 1200,
                    "height": 800,
                    "fixed_ratio": True,
                    "ratio": "3:2",
                },
            },
        )
        self.assertEqual(overrides["Exposure"]["Compensation"], 0.35)
        self.assertEqual(overrides["White Balance"]["Temperature"], 5200)
        self.assertEqual(overrides["White Balance"]["Green"], 1.01)
        self.assertEqual(overrides["Crop"]["W"], 1200)
        self.assertEqual(overrides["Crop"]["FixedRatio"], True)
        self.assertEqual(overrides["Crop"]["Ratio"], "3:2")

    def test_profile_state_fingerprint_is_ordered_and_deterministic(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            first = root / "base.pp3"
            second = root / "source.pp3"
            first.write_text("[Exposure]\nCompensation=0\n", encoding="utf-8")
            second.write_text("[Exposure]\nContrast=2\n", encoding="utf-8")
            state, inputs = rawtherapee_pp3.profile_stack_state(
                [("base_profile", first), ("source_sidecar", second)]
            )
            self.assertEqual([item["role"] for item in state["profile_stack"]], ["base_profile", "source_sidecar"])
            self.assertEqual([item["role"] for item in inputs], ["base_profile", "source_sidecar"])
            self.assertEqual(
                rawtherapee_pp3.canonical_hash(state),
                rawtherapee_pp3.canonical_hash({**state}),
            )


if __name__ == "__main__":
    unittest.main()
