from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import rawtherapee_pp3  # noqa: E402


class RawTherapeePP3Tests(unittest.TestCase):
    def test_parser_and_merge_preserve_unknown_sections_and_fields(self) -> None:
        base = rawtherapee_pp3.PP3Document.parse(
            """# generated by RawTherapee
[Exposure]
Compensation=0.5
UnknownFutureField=keep-me

[Future Module]
Enabled=true
OpaqueCurve=3;0;0;1;1;
""",
            source="base.pp3",
        )
        override = rawtherapee_pp3.PP3Document.parse(
            """[Exposure]
Compensation=1.25

[Lumenflow]
Compiler=test
""",
            source="override.pp3",
        )

        merged = base.merge(override)
        text = merged.to_text()

        self.assertIn("Compensation=1.25", text)
        self.assertIn("UnknownFutureField=keep-me", text)
        self.assertIn("[Future Module]", text)
        self.assertIn("OpaqueCurve=3;0;0;1;1;", text)
        self.assertEqual(merged.get("Exposure", "Compensation"), "1.25")

    def test_compile_profile_layers_starting_state_before_agent_overrides(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            base = root / "base.pp3"
            sidecar = root / "capture.RW2.pp3"
            base.write_text(
                "[Exposure]\nCompensation=0.2\n[Future]\nOpaque=one\n",
                encoding="utf-8",
            )
            sidecar.write_text(
                "[Exposure]\nContrast=3\n[Future]\nSecond=two\n",
                encoding="utf-8",
            )

            text = rawtherapee_pp3.compile_profile_text(
                [base, sidecar],
                overrides={"Exposure": {"Compensation": 0.75}},
            )
            document = rawtherapee_pp3.PP3Document.parse(text)

            self.assertEqual(document.get("Exposure", "Compensation"), "0.75")
            self.assertEqual(document.get("Exposure", "Contrast"), "3")
            self.assertEqual(document.get("Future", "Opaque"), "one")
            self.assertEqual(document.get("Future", "Second"), "two")
            self.assertEqual(document.get("Lumenflow", "Compiler"), rawtherapee_pp3.PP3_COMPILER_VERSION)

    def test_malformed_profile_fails_closed(self) -> None:
        with self.assertRaises(rawtherapee_pp3.PP3ParseError):
            rawtherapee_pp3.PP3Document.parse("Compensation=1\n")
        with self.assertRaises(rawtherapee_pp3.PP3ParseError):
            rawtherapee_pp3.PP3Document.parse("[Exposure]\nnot-a-field\n")

    def test_set_rejects_container_syntax_in_section_and_key(self) -> None:
        document = rawtherapee_pp3.PP3Document.empty()
        for section in ("[bad", "bad]", "bad=section", "bad\n", "bad\r", "bad\x00"):
            with self.subTest(section=section), self.assertRaises(
                rawtherapee_pp3.PP3UnsupportedValue
            ):
                document.set(section, "Key", "value")
        for key in ("[bad", "bad]", "bad=key", "bad\n", "bad\r", "bad\x00"):
            with self.subTest(key=key), self.assertRaises(rawtherapee_pp3.PP3UnsupportedValue):
                document.set("Section", key, "value")

    def test_semantic_mapping_does_not_expose_unverified_native_fields(self) -> None:
        with self.assertRaises(rawtherapee_pp3.PP3UnsupportedValue):
            rawtherapee_pp3.semantic_overrides(
                {"rawtherapee_native": {"Exposure": {"Compensation": 1}}}
            )

    def test_semantic_mapping_rejects_unknown_fields(self) -> None:
        with self.assertRaises(rawtherapee_pp3.PP3UnsupportedValue):
            rawtherapee_pp3.semantic_overrides({"exposure_compensation": 1, "invented": 2})

    def test_semantic_mapping_covers_current_intent_and_pixel_crop(self) -> None:
        overrides = rawtherapee_pp3.semantic_overrides(
            {
                "exposure_compensation": 0.35,
                "temperature": 5200,
                "green": 1.01,
            },
            composition={
                "decision": "crop",
                "crop": {
                    "unit": "pixels",
                    "x": 10,
                    "y": 20,
                    "width": 1200,
                    "height": 800,
                    "fixed_ratio": True,
                    "ratio": "3:2",
                },
            },
        )
        self.assertEqual(overrides["Exposure"]["Compensation"], 0.35)
        self.assertEqual(overrides["White Balance"]["Temperature"], 5200)
        self.assertEqual(overrides["White Balance"]["Green"], 1.01)
        self.assertEqual(overrides["Crop"]["W"], 1200)
        self.assertEqual(overrides["Crop"]["FixedRatio"], True)
        self.assertEqual(overrides["Crop"]["Ratio"], "3:2")

    def test_profile_state_fingerprint_is_ordered_and_deterministic(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            first = root / "base.pp3"
            second = root / "source.pp3"
            first.write_text("[Exposure]\nCompensation=0\n", encoding="utf-8")
            second.write_text("[Exposure]\nContrast=2\n", encoding="utf-8")
            state, inputs = rawtherapee_pp3.profile_stack_state(
                [("base_profile", first), ("source_sidecar", second)]
            )
            self.assertEqual([item["role"] for item in state["profile_stack"]], ["base_profile", "source_sidecar"])
            self.assertEqual([item["role"] for item in inputs], ["base_profile", "source_sidecar"])
            self.assertEqual(
                rawtherapee_pp3.canonical_hash(state),
                rawtherapee_pp3.canonical_hash({**state}),
            )


if __name__ == "__main__":
    unittest.main()
